// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Application.Data;

#nullable disable

namespace Movies.Api.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20251212013413_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.Application.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CastList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RunTime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Age = 13,
                            CastList = "[\"Leonardo DiCaprio\",\"Joseph Gordon-Levitt\",\"Elliot Page\"]",
                            Country = "USA",
                            Cover = "https://filmartgallery.com/cdn/shop/files/Inception-Vintage-Movie-Poster-Original.jpg?v=1738912645",
                            Description = "A skilled thief is offered a chance to have his past crimes forgiven by implanting another person's idea into a target's subconscious.",
                            Director = "Christopher Nolan",
                            Genres = "[\"Action\",\"Sci-Fi\",\"Thriller\"]",
                            Rating = 8.8f,
                            RunTime = 148,
                            Title = "Inception",
                            VideoLink = "https://www.youtube.com/embed/YoHD9XEInc0",
                            YearOfRelease = 2010
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Age = 16,
                            CastList = "[\"Tim Robbins\",\"Morgan Freeman\",\"Bob Gunton\"]",
                            Country = "USA",
                            Cover = "https://image.tmdb.org/t/p/original/5OWFF1DhvYVQiX1yUrBE9CQqO5t.jpg",
                            Description = "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            Genres = "[\"Drama\"]",
                            Rating = 3.3f,
                            RunTime = 142,
                            Title = "The Shawshank Redemption",
                            VideoLink = "https://www.youtube.com/embed/PLl99DlL6b4",
                            YearOfRelease = 1994
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Age = 12,
                            CastList = "[\"Matthew McConaughey\",\"Anne Hathaway\",\"Jessica Chastain\"]",
                            Country = "USA",
                            Cover = "https://m.media-amazon.com/images/I/61ASebTsLpL._AC_UF1000,1000_QL80_.jpg",
                            Description = "A group of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Genres = "[\"Adventure\",\"Drama\",\"Sci-Fi\"]",
                            Rating = 8.6f,
                            RunTime = 169,
                            Title = "Interstellar",
                            VideoLink = "https://www.youtube.com/embed/zSWdZVtXT7E",
                            YearOfRelease = 2014
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Age = 13,
                            CastList = "[\"Christian Bale\",\"Heath Ledger\",\"Aaron Eckhart\"]",
                            Country = "USA",
                            Cover = "https://storage.googleapis.com/pod_public/750/257216.jpg",
                            Description = "Batman faces the Joker, a criminal mastermind who plunges Gotham City into chaos.",
                            Director = "Christopher Nolan",
                            Genres = "[\"Action\",\"Crime\",\"Drama\"]",
                            Rating = 9f,
                            RunTime = 152,
                            Title = "The Dark Knight",
                            VideoLink = "https://www.youtube.com/embed/EXeTwQWrcwY",
                            YearOfRelease = 2008
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Age = 16,
                            CastList = "[\"Song Kang-ho\",\"Lee Sun-kyun\",\"Cho Yeo-jeong\"]",
                            Country = "South Korea",
                            Cover = "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Director = "Bong Joon Ho",
                            Genres = "[\"Comedy\",\"Drama\",\"Thriller\"]",
                            Rating = 8.6f,
                            RunTime = 132,
                            Title = "Parasite",
                            VideoLink = "https://www.youtube.com/embed/5xH0HfJHsaY",
                            YearOfRelease = 2019
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Age = 16,
                            CastList = "[\"Russell Crowe\",\"Joaquin Phoenix\",\"Connie Nielsen\"]",
                            Country = "USA",
                            Cover = "https://i.ebayimg.com/images/g/OcEAAOSwHgdmFp-N/s-l1200.jpg",
                            Description = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.",
                            Director = "Ridley Scott",
                            Genres = "[\"Action\",\"Adventure\",\"Drama\"]",
                            Rating = 8.5f,
                            RunTime = 155,
                            Title = "Gladiator",
                            VideoLink = "https://www.youtube.com/embed/P5ieIbInFpg",
                            YearOfRelease = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
